name: alienpizza
description: "An app to generate a suitable pizza."
publish_to: 'none'

version: 1.0.3+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.13
  cupertino_icons: ^1.0.8
  http: ^1.1.0
  flex_color_picker: ^3.4.1
  audioplayers: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/alien_pizza.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/mainmusic.mp3
    - assets/spacesound.mp3